name: Cypress Tests with Allure and Email

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  cypress-allure:
    runs-on: ubuntu-latest
    continue-on-error: true   # Continue even if tests fail
    steps:
      # ----------------------------
      # Setup
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # ----------------------------
      # Run Cypress specs
      # ----------------------------
      - name: Run Login spec
        run: npx cypress run --spec "cypress/e2e/component/Login.cy.js" --reporter mocha-allure-reporter --reporter-options allureResultsPath=test-results/allure-results

      - name: Run Products spec
        run: npx cypress run --spec "cypress/e2e/component/Products.cy.js" --reporter mocha-allure-reporter --reporter-options allureResultsPath=test-results/allure-results

      # ----------------------------
      # Generate Allure Report
      # ----------------------------
      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          allure generate test-results/allure-results -o test-results/allure-report --clean

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-results/allure-report

      # ----------------------------
      # Send Email with Mailgun
      # ----------------------------
      - name: Send email with Mailgun
        if: always()
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          TO_EMAIL: "muhammadanish2011@gmail.com"
          FROM_EMAIL: "GitHub Actions <no-reply@${{ secrets.MAILGUN_DOMAIN }}>"
        run: |
          if [ ! -f test-results/allure-report/index.html ]; then
            echo "Allure report not found. Skipping email."
            exit 0
          fi

          curl -s --user "api:$MAILGUN_API_KEY" \
          https://api.mailgun.net/v3/$MAILGUN_DOMAIN/messages \
          -F from="$FROM_EMAIL" \
          -F to=$TO_EMAIL \
          -F subject="Cypress Tests Allure Report" \
          -F text="Cypress tests completed. Allure report attached." \
          -F attachment=@test-results/allure-report/index.html
