name: Cypress Tests with Allure Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # allows manual trigger

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Clean report folder
      - name: Prepare Allure results folder
        run: |
          rm -rf test-results/allure-results || true
          mkdir -p test-results/allure-results

      # 5. Run Cypress tests with Allure plugin
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/component/{Login,Products}.cy.js"

      # 6. Install Allure Commandline
      - name: Install Allure CLI
        run: npm install -D allure-commandline

      # 7. Generate Allure report
      - name: Generate Allure Report
        run: |
          npx allure generate ./test-results/allure-results -o ./test-results/allure-report --clean

      # 8. Upload Allure report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-results/allure-report
