name: Cypress Tests with Allure and Email

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  cypress-allure:
    runs-on: ubuntu-latest
    continue-on-error: true   # Continue even if tests fail
    steps:
      # ----------------------------
      # Setup
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
      
      # ----------------------------
      # Create test result folder 
      # ----------------------------

      - name: Create allure results folder
        run: mkdir -p test-results/allure-results

      # ----------------------------
      # Run Cypress specs
      # ----------------------------
      - name: Run Login spec
        run: npx cypress run --spec "cypress/e2e/component/Login.cy.js"  --reporter-options allureResultsPath=test-results/allure-results

      # - name: Run Products spec
      #   run: npx cypress run --spec "cypress/e2e/component/Products.cy.js" --reporter-options allureResultsPath=test-results/allure-results
      - name: List allure results
        run: ls -R test-results/allure-results || echo "No allure results found"

      # ----------------------------
      # Generate Allure Report
      # ----------------------------
      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          allure generate test-results/allure-results -o test-results/allure-report --clean

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-results/allure-report

      # ----------------------------
      # Send Email with Mailgun
      # ----------------------------
      name: Send Email

on: [push]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail via Mailgun
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
          https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN }}/messages \
          -F from="GitHub Actions <mailgun@${{ secrets.MAILGUN_DOMAIN }}>" \
          -F to="yourmail@example.com" \
          -F subject="Hello from GitHub Actions" \
          -F text="This is a test email sent from GitHub Actions using Mailgun."
