name: Cypress on DummyJSON Changes

# Run every 30 minutes (adjust as needed)
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check dummyjson.com for changes
        run: node checkDummyJSON.js || exit 0

      - name: Run Cypress UI tests
        if: ${{ success() }}
        run: npx cypress run
